name: graph
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - rdkit
  - torchaudio
  - cudatoolkit=10.2
  - torchvision
  - pytorch
  - dgl-cuda10.2
  - networkx=2.5
  - tensorboard
  - pip:
      - icecream
      - ogb
      - pyaml
      - seaborn
