experiment_name: 'all_data_cosineLR_no_features'

num_epochs: 1000
batch_size: 128
prefetch_graphs: False
log_iterations: 30
patience: 30
num_train: 110000
loss_func: L1Loss
targets:
  - homo
required_data:
  - pytorch_geometric_graph
  - targets
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared
  - qm9_properties
  - mean_predictor_loss
collate_function: pytorch_geometric_collate

optimizer: Adam
optimizer_params:
  lr: 0.0005

scheduler_step_per_batch: True
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: OneCycleLR
  total_steps: 450000
  anneal_strategy: 'linear'
  max_lr: 2.0e-4

model_type: 'SMP'
model_parameters:
  target_dim: 1
  hidden_dim: 128
  energy_and_force: False
  use_node_features: True
  output_init: GlorotOrthogonal # in DimeNet++, for QM9, 'zeros' for mu, homo, lumo, and zpve; 'GlorotOrthogonal' for alpha, R2, U0, U, H, G, and Cv
  num_spherical: 7
  num_radial: 6
  out_emb_size: 256
  basis_emb_size: 8
  int_emb_size: 64
  propagation_depth: 4
  hidden_channels: 128
  cutoff: 5.0


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt