experiment_name: 'tune'

seed: 6
pretrain_checkpoint: runs2/geomol_qm9/best_model.pt
transfer_layers:
  - gnn.
exclude_from_transfer:
  - batch_norm

dataset: bace_geomol_qm9_featurization
num_epochs: 1000
batch_size: 32
log_iterations: 30
patience: 50
minimum_epochs: 100
loss_func: BCEWithLogitsLoss
metrics:
  - rsquared
  - mean_predictor_loss
  - pearsonr
collate_function: pytorch_geometric_collate

optimizer: Adam
optimizer_params:
  lr: 1.0e-3

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700,700,390]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True



# Model parameters
model_type: 'GeomolGNNWrapper'
model_parameters:
  hidden_dim: 50
  readout_layers: 2
  readout_batchnorm: True
  depth: 3
  n_layers: 2



# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt