experiment_name: 'baseline'

dataset: 'geom_qm9'
num_epochs: 1000
batch_size: 128
prefetch_graphs: True
log_iterations: 30
patience: 30
num_train: 50000
loss_func: L1Loss
targets:
  - ensemblefreeenergy

required_data:
  - complete_graph
  - targets
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared
  - mean_predictor_loss

optimizer: Adam
optimizer_params:
  lr: 1.0e-4

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [1500]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 5.0e-6
  mode: 'min'
  verbose: True

# Model parameters
model_type: 'EGNNEdges'
model_parameters:
  target_dim: 1
  hidden_dim: 128
  reduce_func: 'sum'
  propagation_depth: 7
  dropout: 0.0
  readout_batchnorm: True
  readout_hidden_dim: 128
  readout_layers: 2
  readout_aggregators:
    - min
    - max
    - mean
    - sum
  batch_norm: True


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt