experiment_name: 'tune_NTXent_EGNN_mean_with_distance_aggregator'

pretrain_checkpoint: runs/EGNNEdges_NTXent_EGNN_mean_with_distance_aggregator_10-06_17-49-42/best_checkpoint.pt
transfer_layers:
  - gnn
exclude_from_transfer:
  - batch_norm


num_epochs: 1000
batch_size: 128
prefetch_graphs: True
log_iterations: 30
patience: 50
loss_func: L1Loss
num_train: 50000
targets:
  - homo
features:
  - 'implicit-valence'
  - 'degree'
  - 'hybridization'
  - 'chirality'
  - 'mass'
  - 'electronegativity'
  - 'aromatic-bond'
  - 'formal-charge'
  - 'radical-electron'
  - 'in-ring'
  - 'atomic-number'
e_features:
  - 'bond-type-onehot'
  - 'stereo'
  - 'conjugated'
  - 'in-ring-edges'


required_data:
  - complete_graph
  - targets
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared
  - qm9_properties

optimizer: Adam
optimizer_params:
  lr: 7.0e-5
  weight_decay: 1.0e-11

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700,700,390]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True



# Model parameters
model_type: 'EGNNEdges'
model_parameters:
  target_dim: 1
  hidden_dim: 128
  reduce_func: 'mean'
  propagation_depth: 7
  dropout: 0.0
  readout_batchnorm: True
  readout_hidden_dim: 128
  readout_layers: 2
  readout_aggregators:
    - min
    - max
    - mean
    - sum
  batch_norm: True



# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt