experiment_name: 'molhiv_bigger pna'

dataset: 'molhiv'
num_epochs: 1000
batch_size: 128
log_iterations: 30
patience: 30
loss_func: BCEWithLogitsLoss
metrics:
  - ogb_molhiv

  - rsquared
  - mean_predictor_loss
main_metric: ogb_molhiv
main_metric_goal: max

optimizer: Adam
optimizer_params:
  lr: 0.01
  weight_decay: 3e-6

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [1500]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 20
  min_lr: 1.0e-4
  mode: 'max'
  verbose: True

model_type: 'PNA'
model_parameters:
  target_dim: 1
  hidden_dim: 70
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  readout_hidden_dim: 70
  readout_layers: 2
  dropout: 0.3
  propagation_depth: 4
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - min
    - max
    - mean
    - sum
  pretrans_layers: 1
  posttrans_layers: 1
  residual: True


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt