# continue training from checkpoint:
checkpoint: runs/PNA_NTXent_tiny_3dnet_10hiddendim_03-06_08-59-06/last_checkpoint.pt
targets:
  - homo
required_data:
  - mol_graph
  - complete_graph3d
  - targets
eval_per_epochs: 1
linear_probing_samples: 3000