experiment_name: 'tune_from_drugs_NTXentMultiplePositives_PNAOriginal'

seed: 5
pretrain_checkpoint: runs/PNAOriginal_drugs_NTXentMultiplePositives_123_28-07_09-25-22/best_checkpoint.pt
transfer_layers:
  - gnn
exclude_from_transfer:
  - batch_norm

dataset: 'ogbg-molhiv'
num_epochs: 1000
batch_size: 128
log_iterations: 30
patience: 30
loss_func: BCEWithLogitsLoss
required_data:
  - dgl_graph
  - targets
metrics:
  - rsquared
  - mean_predictor_loss
  - pearsonr
optimizer: Adam
optimizer_params:
  lr: 1.0e-4
collate_function: s_norm_graph_collate

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700,700,390]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True


model_type: 'PNAOriginal'
model_parameters:
  target_dim: 1
  hidden_dim: 70
  last_layer_dim: 70
  mid_batch_norm: True
  last_batch_norm: True
  graph_norm: True
  readout_batchnorm: True
  edge_hidden_dim: 30
  readout_hidden_dim: 100
  readout_layers: 2
  dropout: 0.0
  in_feat_dropout: 0.0
  propagation_depth: 4
  towers: 5
  divide_input_first: False
  divide_input_last: True
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - mean
    - max
    - min
    - sum
  pretrans_layers: 1
  posttrans_layers: 1
  residual: True
  gru: False










# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt