# continue training from checkpoint:
checkpoint: runs/PNALocal_NTXentLocalGlobal_tiny_3dnet_03-06_08-59-05/last_checkpoint.pt
targets: []
required_data:
  - mol_graph
  - mol_graph3d
eval_per_epochs: 0
linear_probing_samples: 3000