# continue training from checkpoint:
checkpoint: runs/PNA_VICReg_27-05_17-16-42/last_checkpoint.pt

metrics:
  - positive_similarity
  - negative_similarity
  - f1_contrastive
  - contrastive_accuracy
  - true_negative_rate
  - true_positive_rate
  - uniformity
  - alignment
  - batch_variance
  - dimension_covariance