# continue training from checkpoint:
checkpoint: runs/PNA_NTXent_tiny_1layer_nodewise_output_10hidden_dim_03-06_08-59-03/last_checkpoint.pt
targets:
  - homo
required_data:
  - mol_graph
  - complete_graph3d
  - targets
eval_per_epochs: 1
linear_probing_samples: 3000