# continue training from checkpoint:
checkpoint: runs/PNA_contrastive_NTXent_small_3dNET_1_layer3Dreadout_27-05_17-16-40/last_checkpoint.pt

metrics:
  - positive_similarity
  - negative_similarity
  - f1_contrastive
  - contrastive_accuracy
  - true_negative_rate
  - true_positive_rate
  - uniformity
  - alignment
  - batch_variance
  - dimension_covariance