experiment_name: 'fine_tune_debug'

pretrain_checkpoint: runs/.contrastive/PNALocal_contrastive_EGNN_NTXentLocalGlobal_25-04_17-53-28/best_checkpoint.pt
transfer_layers:
  - gnn
  - output.fully_connected.0

logdir: runs2
num_epochs: 1000
batch_size: 128
prefetch_graphs: False
log_iterations: 1
patience: 50
loss_func: L1Loss
num_train: 50000
targets:
  - homo
features:
  - 'implicit-valence'
  - 'degree'
  - 'hybridization'
  - 'chirality'
  - 'mass'
  - 'electronegativity'
  - 'aromatic-bond'
  - 'formal-charge'
  - 'radical-electron'
  - 'in-ring'
  - 'atomic-number'
e_features:
  - 'bond-type-onehot'
  - 'stereo'
  - 'conjugated'
  - 'in-ring-edges'


required_data:
  - mol_graph
  - targets
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared
  - qm9_properties


optimizer: Adam
optimizer_params:
  lr: 1.0e-4
transferred_lr: 5.0e-5

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: 30
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.6
  interpolation: linear
  patience: 25
  min_lr: 5.0e-5
  mode: 'min'
  verbose: True

# Model parameters
model_type: 'PNA'
model_parameters:
  hidden_dim: 90
  mid_batch_norm: True
  last_batch_norm: True
  dropout: 0.0
  propagation_depth: 6
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - sum
    - min
    - max
    - mean
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt