experiment_name: 'baseline'



num_epochs: 1000
batch_size: 128
trainer: geomol
log_iterations: 30
patience: 30
loss_func: L1Loss
num_train: 50000
required_data:
  - pytorch_geometric_graph
  - targets
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared
  - qm9_properties
collate_function: pytorch_geometric_collate

optimizer: Adam
optimizer_params:
  lr: 7.0e-5
  weight_decay: 1.0e-11

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True



# Model parameters
model_type: 'Geomol'
model_parameters:
  hyperparams:
    alpha_mlp:
      n_layers: 2
    c_mlp:
      n_layers: 1
    coord_pred:
      n_layers: 2
    d_mlp:
      n_layers: 1
    encoder:
      n_head: 2
    global_transformer: false
    gnn1:
      depth: 3
      n_layers: 2
    gnn2:
      depth: 3
      n_layers: 2
    h_mol_mlp:
      n_layers: 1
    loss_type: ot_emd
    model_dim: 50
    n_model_confs: 10
    n_true_confs: 10
    random_alpha: false
    random_vec_dim: 10
    random_vec_std: 5.0
    teacher_force: false
  num_edge_features: 4
  num_node_features: 44



# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt